imports:
    - { resource: dev_config.yml }
    - { resource: prod_config.yml }
    - { resource: test/parameters.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
