# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory: { memory: ~ }
#        custom_login_provider:
#            id: AppBundle\Model\Custom\UserQuery
#        common_login_provider:
#            id: AppBundle\Model\Common\UserQuery
#        panel_user:
#            chain:
#                providers: [custom_login_provider, common_login_provider]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login_panel:
#            pattern: ^/rest/login$
#            methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#
#            guard:
#              authenticators:
#                - rest_authenticator
#            security: true
#
#            stateless: true
#            provider: common_login_provider
#
#        login_channel:
#            pattern: ^/rest/.+/login$
#            methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#
#            guard:
#              authenticators:
#                - rest_authenticator
#            security: true
#
#            stateless: true
#            provider: custom_login_provider
#
#        rest:
#            pattern: ^/rest/
#            methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#
#            guard:
#              authenticators:
#                - rest_authenticator
#            security: true
#
#            stateless: true
#            provider: panel_user
        pub:
            anonymous: ~
            security: false

#    access_control:
#        - { path: ^/rest/reset_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/rest/config/?$, methods: [GET, POST], roles: ROLE_PANEL }
#        - { path: ^/rest/login/?$, roles: ROLE_USER }
#        - { path: ^/rest/, roles: ROLE_PANEL }
    role_hierarchy:
        ROLE_BANNED_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_PANEL: ROLE_USER
